name: consumo_electrico_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^5.5.1
  equatable: ^2.0.5
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.11
  google_fonts: ^6.2.1
  iconly: ^1.0.1
  lottie: ^3.2.0
  modal_progress_hud_nsn: ^0.5.1
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
  fonts:
    - family: SF-Pro-Text
      fonts:
        - asset: fonts/SF-Pro-Text-Regular.otf
